# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c160f608fd766c6f9d523626202d7973695f34349a13e9c9936d87b12d0b01e560bdde4d6f97c81d0640b5e6b6f81aaecace0fa477c0d3445b69ce5091ccac9d

test:
  secret_key_base: 4d6feed63b915cb8c8cbdcb4c394e47b6b0ca738d87e7262ef6083931f1dc37f0bb39c18d57797d09e77450ac36e1152b844b9906a6d9429ac1038dfe5930abe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
